### ISSUE TITLE
Visitor: search product listings

### ISSUE THREAD

**Issue by ErikaNewland** [1707-grace-shopper-sh/grace-shopper#17]
Audience: visitor
Story: ...search product listings, so that I can find specific products I want by name
Implementation: In search component, create a search function that
1.  searches through products on props for input match (be careful of case)
2.  redirects to a either: (a) no product found component view or (b) individual product component, passing in the matched product object
3.  Manage URL bar with redirect

**Comment by ebeastlake** [comment]
Currently works by rendering all products with partial match; I think this is better than switching to individual product component. Let me know if you disagree!
